### ISSUE TITLE
Bugs when capturing screenshot

### ISSUE THREAD

**Issue by eithan1231** [gilyes/Screenshot.NET#1]
As you're selecting what part of the screen you wish to screenshot, it has a tendency to preview the wrong area. This doesn't occur 100% of the time, only sometimes. But when you release your mouse, it will screencapture the correct portion of your screen, just as it's previewing it screws up.

Context:
I have 3 screens @ 1080p, each sitting besides eachother.
CaprturingRegion with no parameters.

Observations: only happens when you're not dragging from top-left to bottom-right.

**Comment by gilyes** [comment]
Fixed, version 1.1 released to nuget.
