### ISSUE TITLE
Screen scaling bug

### ISSUE THREAD

**Issue by h77ps** [gilyes/Screenshot.NET#2]
I've found a bug. When the primary display (or another display) is set to any scaling other than 100% the SystemParameters.VirtualScreenLeft, SystemParameters.VirtualScreenTop, SystemParameters.VirtualScreenWidth, SystemParameters.VirtualScreenHeight, SystemParameters.PrimaryScreenWidth, SystemParameters.PrimaryScreenHeight all return inaccurate dimensions. 

For instance I have a 3 monitor setup (2nd display is primary) all 1920 x 1080. When all displays are set to 100% scaling the values are the following:
SystemParameters.VirtualScreenLeft = -1920
SystemParameters.VirtualScreenTop = 0
SystemParameters.VirtualScreenWidth = 5760
SystemParameters.VirtualScreenHeight = 1080
All the values here are correct!

When second display (primary) is set to 125% scaling the values are the following:
SystemParameters.VirtualScreenLeft = -1536
SystemParameters.VirtualScreenTop = 0
SystemParameters.VirtualScreenWidth = 4608
SystemParameters.VirtualScreenHeight = 864
All the values here are incorrect!

When those scaled values are fed into graphics.CopyFromScreen the resulting bitmap image is cropped as graphics.CopyFromScreen expects actual resolution pixels, not the scaled resolution pixels that SystemParameters provides.

Edit:
By the way this is occurring on Windows 10 and the application using the library is set to be DPI aware so that it scales with windows.

**Comment by zhoujin7** [comment]
I have the same problem.  I found https://github.com/ShareX/ShareX works well.

**Comment by gilyes** [comment]
For the scenario described here the application must enable per-monitor DPI settings. Updated the demo application with a manifest file that does that.

**Comment by XIIREX** [comment]
I have the same issue. I've tried to add the DPI Awareness per screen and downloading the Demo where it is already setup. But in both cases it doesn't seem to work.

Any idea why? @gilyes

**Comment by StormRSA** [comment]
@XIIREX  did you manage to find a fix?
